# Get data into data array and print descriptives

In [20]:
import os
import pandas as pd
# os.chdir('../notebooks/social_planets/')
print(os.path.abspath(os.curdir))
gender=pd.read_csv('n87_sex.csv')
print(gender)
print(gender.columns)
indices_change=[11, 66, 7, 82, 51, 81, 45, 72, 1, 48, 10, 79, 39, 86, 80, 42, 15, 67, 47, 69, 6, 41, 43,
                71, 54, 31, 59, 22, 62, 3, 13, 16, 84, 52, 85, 17, 73, 57, 9, 50, 60, 35, 75, 38, 55, 24, 68, 
                83, 78, 58, 0, 18, 46, 44, 70, 63, 61, 49, 64, 30, 26, 
                14, 4, 37, 25, 32, 53, 76, 29, 21, 65, 34, 23, 12, 20, 8, 77, 19, 2, 
                5, 33, 27, 56, 74, 28, 40, 36]
print(gender['sex'])
gender_correct_order=[gender['sex'][i] for i in indices_change]
gender_array=np.asarray(gender_correct_order)
# np.save('gender_87subs',gender_array)

/home/paul/MPC_Files/projects/Do_Sharp_Telzer_ProjectARC/notebooks/social_planets
        ID  sex
0   NT1003    0
1   NT1010    1
2   NT1012    0
3   NT1018    0
4   NT1027    1
..     ...  ...
82  NT2215    0
83  NT2220    1
84  NT2221    1
85  NT2222    1
86  NT2228    1

[87 rows x 2 columns]
Index(['ID', 'sex'], dtype='object')
0     0
1     1
2     0
3     0
4     1
     ..
82    0
83    1
84    1
85    1
86    1
Name: sex, Length: 87, dtype: int64


In [11]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import os 
import csv
from scipy.stats import spearmanr as corrS
from scipy.stats import ttest_ind
import seaborn as sns
import matplotlib.pyplot as plt

path_files='/home/paul/MPC_Files/projects/Do_Sharp_Telzer_ProjectARC/social_planets_data/data_files'
os.chdir(path_files)
y=np.load('order_condition.npy')
order_var=[]
for i in y:
    if i[0]==2:
        order_var.append(1)
    else:
        order_var.append(0)
        
csvfiles=[x for x in os.listdir(os.curdir) if x.endswith('-.csv')]

subs_dont_know=np.load('subs_dont_know.npy')
criteria_inclusion=np.load('subs_not_meet_criteria_combined_pop_lik_posttask_qs.npy')

subs_dont_know=[]
unpop_lik=[]
own_rating=[]
unpop_cool=[]
pop_lik=[]
pop_cool=[]
combo_pop=[]
combo_unpop=[]
acceptable=[1,2,3,4]
subs_ttp=[]
# soc_stat_df=pd.read_csv('sub_soc_stats_socialpref.csv')
counter=-1

order_v=[]
csvfiles=[sub for sub in csvfiles if sub not in subs_dont_know]
failed_manipulation_check=['3162-.csv', '3040-.csv', '3056-.csv', 
                           '3132-.csv', '3061-.csv', '3198-.csv', 
                           '3226-.csv', '3158-.csv', '3028-.csv', 
                           '3136-.csv', '3068-.csv', '3172-.csv']
csvfiles=[sub for sub in csvfiles if sub not in failed_manipulation_check]
x=gender['ID'].tolist()
x=['3'+i[3:]+'-.csv' for i in x]
indices_change=[]
for i in csvfiles:
    c=0
    for j in x:
        if i==j:
            indices_change.append(c)
        c+=1
print(indices_change)
    
load
high_status_failed=[]
low_status_failed=[]
#iterate through csv files that has self-report data
c_sub=1
for sub in csvfiles:
    
    counter+=1
    df=pd.read_csv(sub)
    name_rounds=df.Procedure
    likability=df['PostScan4.RESP']
    cool=df['PostScan2.RESP']
    know_person=df['PostScan1.RESP']
    row=0
    if 'Unpop' in name_rounds[174]:
        order_v.append(1)
    else:
        order_v.append(0)


    for q_name in name_rounds:
        if know_person[row] in acceptable:
            if know_person[row]==3:
#                 print('didnt know')
#                 print('subject csv: {}'.format(sub))
                subs_dont_know.append(sub)
        if likability[row] in acceptable:
            if q_name.endswith('Unpop'):
                unpop_lik.append(likability[row])
            else:
                pop_lik.append(likability[row])
        if cool[row] in acceptable:
            if q_name.endswith('Unpop'):
                unpop_cool.append(cool[row])
            else:
                pop_cool.append(cool[row])
        if cool[row] in acceptable and likability[row] in acceptable:
            if q_name.endswith('Unpop'):
                if sub in failed_manipulation_check:
                    low_status_failed.append((likability[row]+cool[row])/2.0)
                else:
                    combo_unpop.append((likability[row]+cool[row])/2.0)
                
            else:
                if sub in failed_manipulation_check:
                    high_status_failed.append((likability[row]+cool[row])/2.0)
                else:
                    combo_pop.append((likability[row]+cool[row])/2.0)
        row+=1
# print('num subs dont know')
# print(len(subs_dont_know))
print('mean high status : {}, SD: {}'.format(np.mean(combo_pop),np.std(combo_pop)))
print('mean low status : {}, SD: {}'.format(np.mean(combo_unpop),np.std(combo_unpop)))
t,p=ttest_ind(combo_pop,combo_unpop)
print('t:{},p-val:{}'.format(t,p))
stop

# np.save('subs_dont_know',subs_dont_know)
# np.save('order_variable_fixed',order_v)               
#convert se;f report data to arrays  
up_liks=np.asarray(unpop_lik)

above_avg_unpop_lik=0
counter=0
bad_ps=[]
for i in up_liks:
    if i>3:
        above_avg_unpop_lik+=1
        bad_ps.append(counter)
    counter+=1
print('{} liked low status peer at 4'.format(above_avg_unpop_lik))
print('indicies of aberrant subs on unpop: {}'.format(bad_ps))       

up_cools=np.asarray(combo_unpop)

p_liks=np.asarray(pop_lik)
p_cools=np.asarray(combo_pop)

below_avg_pop_lik=0
bad_pa=[]
counter=0
for i in p_liks:
    if i<2:
        below_avg_pop_lik+=1
        bad_pa.append(counter)
    counter+=1
print('{} liked high status peer at 1'.format(below_avg_pop_lik))




#create array of differences within subjects for which peer type is liked more (or equally)
difference_liks1=p_liks-up_liks
print('difference likeability: {}'.format(difference_liks1))



difference_liks=p_cools-up_cools
print('difference combo: {}'.format(difference_liks))

subs_not_meet_criteria=[]
counter=0
bad_pa=[]

for i in range(len(difference_liks)):
    if difference_liks[i]<0:
        subs_not_meet_criteria.append(counter)
        bad_pa.append(counter)
    counter+=1
print(len(subs_not_meet_criteria))
print('indicies of bad subs on unpop: {}'.format(bad_pa))  

remove_subs=[]
for i in bad_pa:
    remove_subs.append(csvfiles[i])
    
print('removed subs failure meet criteria: {}'.format(remove_subs))

load
#np.save('subs_not_meet_criteria_combined_pop_lik_posttask_qs',subs_not_meet_criteria)

stop
#compute subgroups within differences array just computed
# G1 - composed of one subgroup that likes unpopular peers more & one subgroup that likes both equally
# G2 - composed of participants that like popular peers mroe

num_negative=0
num_equal=0
equal_vals=[]
negative_vals=[]
neg_unpop=[]
positive_vals=[]
counter=-1
positive_subs=[['G2_popMore']]
equal_subs=[['G1_equal']]
neg_subs=[['G1_unpopMore']]

just_negs=[]
equal_all=[]

likeable_subs=[1 if val>0 else 0 for x,val in enumerate(difference_liks)]
# print('length likeable subs var: {}'.format(len(likeable_subs)))
likeable_subs_no_equals=[]
likeable_subs_no_negs=[]
likeable_subs_three=[]
for i in difference_liks:
    counter+=1
    if i<0:
        num_negative+=1
        negative_vals.append(pop_lik[counter])
        neg_unpop.append(unpop_lik[counter])
        likeable_subs_no_equals.append(0)
        likeable_subs_three.append(-1)
        neg_subs.append([csvfiles[counter]])
        just_negs.append(csvfiles[counter])
    elif i==0:
        num_equal+=1
        likeable_subs_no_negs.append(0)
        likeable_subs_three.append(0)
        equal_vals.append(unpop_lik[counter])
        equal_subs.append([csvfiles[counter]])
        equal_all.append(csvfiles[counter])
    else:
        likeable_subs_three.append(1)
        likeable_subs_no_equals.append(1)
        likeable_subs_no_negs.append(1)
        positive_subs.append([csvfiles[counter]])
        positive_vals.append(pop_lik[counter])
        just_negs.append(csvfiles[counter])
        equal_all.append(csvfiles[counter])

lik_pops=[]
unlik_pops=[]
lik_unpops=[]
unlik_unpops=[]
lik_vals=[]
unlik_vals=[]
for i in range(len(difference_liks)):
    if likeable_subs[i]==0:
        unlik_vals.append(difference_liks[i])
        unlik_pops.append(pop_lik[i])
        unlik_unpops.append(unpop_lik[i])
        
    else:
        lik_vals.append(difference_liks[i])
        lik_pops.append(pop_lik[i])
        lik_unpops.append(unpop_lik[i])
        
        
print('pop rated by Prefer Low:')
print(np.mean(negative_vals),np.std(negative_vals),np.ptp(negative_vals))
print('unpop rated by Prefer Low:')
print(np.mean(neg_unpop),np.std(neg_unpop),np.ptp(neg_unpop))
print('pop rated by Equals:')
print(np.mean(equal_vals),np.std(equal_vals),np.ptp(equal_vals))
print('unpop rated by Prefer High')
print(np.mean(lik_unpops),np.std(lik_unpops),np.ptp(lik_unpops))
print('pop rated by prefer High')
print(np.mean(lik_pops),np.std(lik_pops),np.ptp(lik_pops))

#save .csv file with which subjects belong to which subgroup
eq=np.asarray(equal_subs)
neg=np.asarray(neg_subs)
pos=np.asarray(positive_subs)
all_ids=np.concatenate((neg,eq,pos),axis=0)
# with open('group_IDs.csv', 'a') as f:
#     csv.writer(f).writerows(all_ids)


#descriptive statistics on subgroup
threes=np.asarray(likeable_subs_three)
noequs=np.asarray(likeable_subs_no_equals)
nonegs=np.asarray(likeable_subs_no_negs)
print('Number of equal subs: {}'.format(len(equal_subs)))
np.save('popularity_subs_allthree_known',threes)
print('here')
print(stop)
# print('number avg popular G2 : {}'.format(np.mean(positive_vals)))
# print('')
# print('number avg equal: {}'.format(np.mean(equal_vals)))
# print('')
# print('number avg popular subgroup like unpop more: {}'.format(np.mean(negative_vals)))
# print('')
# t,p=ttest_ind(equal_vals,negative_vals,equal_var=False)
# print('t: {} pval: {} diff b/t G1 subgroups'.format(t,p))
# print('')
# t,p=ttest_ind(equal_vals,positive_vals,equal_var=False)
# print('t: {} pval: {} diff b/t G1 equals and G2'.format(t,p))

likeable_subs=[1 if val>0 else 0 for x,val in enumerate(difference_liks)]
print(likeable_subs)
stop
# np.save('likeable_subs_justknown',likeable_subs)

zeros=0

#extract likability ratings for popular and unpopular peers across G1 and G2 for main displays
lik_pops=[]
unlik_pops=[]
lik_unpops=[]
unlik_unpops=[]
lik_vals=[]
unlik_vals=[]
for i in range(len(difference_liks)):
    if likeable_subs[i]==0:
        unlik_vals.append(difference_liks[i])
        unlik_pops.append(pop_lik[i])
        unlik_unpops.append(unpop_lik[i])
        
    else:
        lik_vals.append(difference_liks[i])
        lik_pops.append(pop_lik[i])
        lik_unpops.append(unpop_lik[i])




### GRAPH DESCRIPTIVES OF EACH SUBGROUP

unique_elements, counts_elements = np.unique(lik_vals, return_counts=True)
counts_elements=counts_elements/np.sum(counts_elements)
ax=sns.barplot(x=unique_elements,y=counts_elements,palette='Blues')
ax.set(title='Difference Likability G2',xlabel='difference pop-unpop')
plt.show()
unique_elements, counts_elements = np.unique(unlik_vals, return_counts=True)
counts_elements=counts_elements/np.sum(counts_elements)

ax=sns.barplot(x=unique_elements,y=counts_elements,palette='Blues')
ax.set(title='Difference Likability G1:',xlabel='difference pop-unpop')
plt.show()
unique_elements, counts_elements = np.unique(lik_pops, return_counts=True)
counts_elements=counts_elements/np.sum(counts_elements)

ax=sns.barplot(x=unique_elements,y=counts_elements,palette='Oranges')
ax.set(title='G2 Likeability Ratings Popular Peers:',xlabel='likeability rating')
plt.show()
unique_elements, counts_elements = np.unique(unlik_pops, return_counts=True)
counts_elements=counts_elements/np.sum(counts_elements)

ax=sns.barplot(x=unique_elements,y=counts_elements,palette='Blues')
ax.set(title='G1 Likeability Ratings Popular Peers:',xlabel='likeability rating')
plt.show()
unique_elements, counts_elements = np.unique(lik_unpops, return_counts=True)
counts_elements=counts_elements/np.sum(counts_elements)

ax=sns.barplot(x=unique_elements,y=counts_elements,palette='Oranges')
ax.set(title='G2 Likeability Ratings Unpopular Peers:',xlabel='likeability rating')
plt.show()

unique_elements, counts_elements = np.unique(unlik_unpops, return_counts=True)
counts_elements=counts_elements/np.sum(counts_elements)
ax=sns.barplot(x=unique_elements,y=counts_elements,palette='Blues')
ax.set(title='G1 Likeability Ratings Unpopular Peers:',xlabel='likeability rating')
plt.show()

unique_elements, counts_elements = np.unique(equal_vals, return_counts=True)
counts_elements=counts_elements/np.sum(counts_elements)

ax=sns.barplot(x=unique_elements,y=counts_elements,palette='Greens')
ax.set(title='Distribution for individuals that liked equally',xlabel='likeability rating')
plt.show()


unique_elements, counts_elements = np.unique(negative_vals, return_counts=True)
counts_elements=counts_elements/np.sum(counts_elements)

ax=sns.barplot(x=unique_elements,y=counts_elements,palette='Greens')
ax.set(title='Distribution for individuals that liked unpopular peers more',xlabel='likeability rating')
plt.show()





[11, 66, 7, 82, 51, 81, 45, 72, 1, 48, 10, 79, 39, 86, 80, 42, 15, 67, 47, 69, 6, 41, 43, 71, 54, 31, 59, 22, 62, 3, 13, 16, 84, 52, 85, 17, 73, 57, 9, 50, 60, 35, 75, 38, 55, 24, 68, 83, 78, 58, 0, 18, 46, 44, 70, 63, 61, 49, 64, 30, 26, 14, 4, 37, 25, 32, 53, 76, 29, 21, 65, 34, 23, 12, 20, 8, 77, 19, 2, 5, 33, 27, 56, 74, 28, 40, 36]


NameError: name 'load' is not defined

In [9]:
print(len(likeable_subs_three))

96


# Calculate D-prime on all three rounds within condition

In [12]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import os 
from scipy.stats import spearmanr as corrS
from scipy.stats import ttest_ind
import csv

path_files='/Users/paulsharp/Documents/Eva_Telzer_Collaboration/social_planets_data'
csv_files=[x for x in os.listdir(os.curdir) if x.endswith('-.csv')]
subs_dont_know=np.load('subs_dont_know.npy')
data_structure_dprime=np.zeros((96,3,3))
sub_counter=0
sub_names=[['Sub ID']]



actual_sub_counter=0
cond_counter=0
for sub in csv_files:
    if sub not in subs_dont_know:
        sub_name=sub[:-5]
        sub_names.append([sub_name])
        df=pd.read_csv(sub)
        name_rounds=df.Procedure
        counter=0 #trial within a block

        index=0
        hits=0
        fa=0
        condition_data=[]
        bl_counter=0
        unpop_counter=0
        pop_counter=0
        for name in name_rounds:
            if counter==21: #21 trials per round within a condition, 3 rounds per condition
                hit_rate=hits/14.0

                if hit_rate==1:
                    hit_rate=0.99
    #             print('hit_rate: {}'.format(hit_rate))
                fa_rate=fa/7.0
                if fa_rate==0:
                    fa_rate=.01
    #             print('fa_rate: {}'.format(fa_rate))
                dprime = stats.norm.ppf(hit_rate) - stats.norm.ppf(fa_rate)
                if dprime<0:
                    dprime=0
    #             print("d prime: {}".format(dprime))
                cond_counter+=1
                if 'Unpop' in name_rounds[index-5]:
                    data_structure_dprime[actual_sub_counter,1,unpop_counter]=dprime
                    unpop_counter+=1
                    if unpop_counter==3:
    #                     order_conditions[actual_sub_counter,0]=order
    #                     order+=1
                        unpop_counter=0

                elif 'BaselineStim' in name_rounds[index-5]:
                    data_structure_dprime[actual_sub_counter,0,bl_counter]=dprime
                    bl_counter+=1
                    if bl_counter==3:
                        bl_counter=0

                elif 'Pop' in name_rounds[index-5]:
                    data_structure_dprime[actual_sub_counter,2,pop_counter]=dprime
                    pop_counter+=1
                    if pop_counter==3:
    #                     order_conditions[actual_sub_counter,1]=order
    #                     order+=1
                        pop_counter=0
                if cond_counter==9:
                    actual_sub_counter+=1
                    cond_counter=0
                    order=1

                #reset condition data holder and counter
                hits=0
                fa=0
                condition_data=[]
                counter=0

            try: 
                if name.endswith('Proc'):
                    counter+=1
        #             print(counter)
                    if int(df.Go_NoGo[index])==1:
                        current_row=df.iloc[index].tolist()
                        if '{SPACE}' in current_row:
                            condition_data.append(1)
                            hits+=1
                        else:
                            condition_data.append(0)
                    else:
                        current_row=df.iloc[index].tolist()
                        if '{SPACE}' in current_row:
                            condition_data.append(0)
                            fa+=1
                        else:
                            condition_data.append(1)
                elif name.endswith('Proc1'):
                    counter+=1
        #             print(counter)
                    if int(df.Go_NoGo[index])==1:
                        current_row=df.iloc[index].tolist()
                        if '{SPACE}' in current_row:
                            condition_data.append(1)
                            hits+=1
                        else:
                            condition_data.append(0)
                    else:
                        current_row=df.iloc[index].tolist()
                        if '{SPACE}' in current_row:
                            condition_data.append(0)
                            fa+=1
                        else:
                            condition_data.append(1)
            except:
                err='not a readable row'

            index+=1
        sub_counter+=1  
    
np.save('data_justknown_subs',data_structure_dprime)
# np.save('order_justLiked',order_conditions)
print(data_structure_dprime)
#np.save('order_conditions_greaterthan0',order_conditions)
#np.save('data__lessthan1diff',data_structure_dprime)
#np.savetxt('data_dprime_raw.csv',data_structure_dprime,delimiter=',')
print('DONE')

[[[0.97165098 2.1463355  0.39766327]
  [2.8922967  1.64524616 0.89928497]
  [1.63351935 3.3939184  0.89928497]]

 [[1.13189764 1.35758743 1.28522142]
  [0.97165098 3.3939184  1.24758289]
  [1.63351935 2.8922967  2.13514105]]

 [[2.53280432 2.03118261 1.24758289]
  [1.64524616 2.53280432 2.03118261]
  [2.53280432 3.3939184  3.3939184 ]]

 [[3.11798648 3.3939184  3.3939184 ]
  [2.53280432 3.79158167 3.3939184 ]
  [3.79158167 3.79158167 3.3939184 ]]

 [[3.11798648 2.53280432 1.64524616]
  [1.64524616 2.03118261 2.53280432]
  [0.39766327 1.35758743 0.97165098]]

 [[1.35758743 0.97165098 1.35758743]
  [0.         0.         2.53280432]
  [2.13514105 1.63351935 2.13514105]]

 [[1.63351935 2.13514105 2.03118261]
  [2.03118261 3.79158167 3.3939184 ]
  [3.3939184  2.53280432 2.53280432]]

 [[1.13189764 2.03118261 1.28522142]
  [0.61162624 0.54611873 1.25877735]
  [0.         0.97165098 2.8922967 ]]

 [[2.53280432 3.3939184  2.8922967 ]
  [2.13514105 1.64524616 2.1463355 ]
  [3.3939184  4.652695